FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY Sake/ ./
RUN dotnet publish Sake.csproj -c Release -o /out --self-contained false
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /out/ ./
ENTRYPOINT ["dotnet", "/app/Sake.dll"]
